<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/09/25 07:13:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=juulchin',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
